version: '3'
services:
  php:
    build:
      context: ./docker
      dockerfile: php.Dockerfile
    container_name: ${APP_NAME:?err}-php
    volumes:
      - './app:/var/www/html'
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME:?err}-nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'php'
    volumes:
      - './app:/var/www/html'
      - './config/nginx:/etc/nginx/conf.d'

  mariadb:
    image: mariadb:latest
    container_name: ${APP_NAME:?err}-mariadb
    restart: 'on-failure'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    ports:
      - 3306:3306
    volumes:
      - ${PWD}

  adminer:
    image: adminer:latest
    container_name: ${APP_NAME:?err}-adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - 8080:8080
